GET http://127.0.0.1:4000/api/testAuth
authorization: GOOGLE eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5IiwiaWF0IjoxNjU5NTU4NDAyLCJleHAiOjE2NTk1NTkwMDJ9.POrHpRGhxrjRPDuY5KTyYM74GhY59-AZcIBTtpr3fY0

###
GET http://127.0.0.1:4000/api/testAuthOnlySACRED
authorization: SACRED eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5IiwiaWF0IjoxNjU5NTU4NDAyLCJleHAiOjE2NTk1NTkwMDJ9.POrHpRGhxrjRPDuY5KTyYM74GhY59-AZcIBTtpr3fY0

###
GET http://127.0.0.1:4000/api/testAuthOnlySACRED
authorization: GOOGLE eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5IiwiaWF0IjoxNjU5NTU4NDAyLCJleHAiOjE2NTk1NTkwMDJ9.POrHpRGhxrjRPDuY5KTyYM74GhY59-AZcIBTtpr3fY0

###
GET http://127.0.0.1:4000/api/test